[2025-02-13T08:21:21.727+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-13T08:21:21.749+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: transform_data_dag.dbt_run manual__2025-02-13T08:21:14.147237+00:00 [queued]>
[2025-02-13T08:21:21.760+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: transform_data_dag.dbt_run manual__2025-02-13T08:21:14.147237+00:00 [queued]>
[2025-02-13T08:21:21.762+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-02-13T08:21:21.777+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): dbt_run> on 2025-02-13 08:21:14.147237+00:00
[2025-02-13T08:21:21.784+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=5896) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-02-13T08:21:21.786+0000] {standard_task_runner.py:72} INFO - Started process 5897 to run task
[2025-02-13T08:21:21.784+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'transform_data_dag', 'dbt_run', 'manual__2025-02-13T08:21:14.147237+00:00', '--job-id', '69', '--raw', '--subdir', 'DAGS_FOLDER/transform_data_dag.py', '--cfg-path', '/tmp/tmp6m3y5zez']
[2025-02-13T08:21:21.787+0000] {standard_task_runner.py:105} INFO - Job 69: Subtask dbt_run
[2025-02-13T08:21:21.804+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:209 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-02-13T08:21:21.839+0000] {task_command.py:467} INFO - Running <TaskInstance: transform_data_dag.dbt_run manual__2025-02-13T08:21:14.147237+00:00 [running]> on host 89bb8c6379b5
[2025-02-13T08:21:21.897+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/utils/log/secrets_masker.py:84 DeprecationWarning: The sensitive_variable_fields option in [admin] has been moved to the sensitive_var_conn_names option in [core] - the old setting has been used, but please update your config.
[2025-02-13T08:21:21.929+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='transform_data_dag' AIRFLOW_CTX_TASK_ID='dbt_run' AIRFLOW_CTX_EXECUTION_DATE='2025-02-13T08:21:14.147237+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-13T08:21:14.147237+00:00'
[2025-02-13T08:21:21.930+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-02-13T08:21:21.947+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-02-13T08:21:21.949+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'cd /opt/airflow/dags/dbt/***_project && dbt run']
[2025-02-13T08:21:21.956+0000] {subprocess.py:99} INFO - Output:
[2025-02-13T08:21:24.373+0000] {subprocess.py:106} INFO - [0m08:21:24  Running with dbt=1.8.7
[2025-02-13T08:21:24.696+0000] {subprocess.py:106} INFO - [0m08:21:24  Registered adapter: ***=1.9.0
[2025-02-13T08:21:25.377+0000] {subprocess.py:106} INFO - [0m08:21:25  Encountered an error:
[2025-02-13T08:21:25.378+0000] {subprocess.py:106} INFO - keyword argument repeated: post_hook (<template>, line 15)
[2025-02-13T08:21:25.381+0000] {subprocess.py:106} INFO - [0m08:21:25  Traceback (most recent call last):
[2025-02-13T08:21:25.382+0000] {subprocess.py:106} INFO -   File "/home/airflow/.local/lib/python3.12/site-packages/dbt/cli/requires.py", line 138, in wrapper
[2025-02-13T08:21:25.383+0000] {subprocess.py:106} INFO -     result, success = func(*args, **kwargs)
[2025-02-13T08:21:25.383+0000] {subprocess.py:106} INFO -                       ^^^^^^^^^^^^^^^^^^^^^
[2025-02-13T08:21:25.384+0000] {subprocess.py:106} INFO -   File "/home/airflow/.local/lib/python3.12/site-packages/dbt/cli/requires.py", line 101, in wrapper
[2025-02-13T08:21:25.385+0000] {subprocess.py:106} INFO -     return func(*args, **kwargs)
[2025-02-13T08:21:25.386+0000] {subprocess.py:106} INFO -            ^^^^^^^^^^^^^^^^^^^^^
[2025-02-13T08:21:25.386+0000] {subprocess.py:106} INFO -   File "/home/airflow/.local/lib/python3.12/site-packages/dbt/cli/requires.py", line 218, in wrapper
[2025-02-13T08:21:25.387+0000] {subprocess.py:106} INFO -     return func(*args, **kwargs)
[2025-02-13T08:21:25.387+0000] {subprocess.py:106} INFO -            ^^^^^^^^^^^^^^^^^^^^^
[2025-02-13T08:21:25.388+0000] {subprocess.py:106} INFO -   File "/home/airflow/.local/lib/python3.12/site-packages/dbt/cli/requires.py", line 247, in wrapper
[2025-02-13T08:21:25.389+0000] {subprocess.py:106} INFO -     return func(*args, **kwargs)
[2025-02-13T08:21:25.389+0000] {subprocess.py:106} INFO -            ^^^^^^^^^^^^^^^^^^^^^
[2025-02-13T08:21:25.390+0000] {subprocess.py:106} INFO -   File "/home/airflow/.local/lib/python3.12/site-packages/dbt/cli/requires.py", line 294, in wrapper
[2025-02-13T08:21:25.390+0000] {subprocess.py:106} INFO -     return func(*args, **kwargs)
[2025-02-13T08:21:25.391+0000] {subprocess.py:106} INFO -            ^^^^^^^^^^^^^^^^^^^^^
[2025-02-13T08:21:25.391+0000] {subprocess.py:106} INFO -   File "/home/airflow/.local/lib/python3.12/site-packages/dbt/cli/requires.py", line 320, in wrapper
[2025-02-13T08:21:25.392+0000] {subprocess.py:106} INFO -     ctx.obj["manifest"] = parse_manifest(
[2025-02-13T08:21:25.392+0000] {subprocess.py:106} INFO -                           ^^^^^^^^^^^^^^^
[2025-02-13T08:21:25.393+0000] {subprocess.py:106} INFO -   File "/home/airflow/.local/lib/python3.12/site-packages/dbt/parser/manifest.py", line 1898, in parse_manifest
[2025-02-13T08:21:25.394+0000] {subprocess.py:106} INFO -     manifest = ManifestLoader.get_full_manifest(
[2025-02-13T08:21:25.394+0000] {subprocess.py:106} INFO -                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-02-13T08:21:25.395+0000] {subprocess.py:106} INFO -   File "/home/airflow/.local/lib/python3.12/site-packages/dbt/parser/manifest.py", line 330, in get_full_manifest
[2025-02-13T08:21:25.396+0000] {subprocess.py:106} INFO -     manifest = loader.load()
[2025-02-13T08:21:25.397+0000] {subprocess.py:106} INFO -                ^^^^^^^^^^^^^
[2025-02-13T08:21:25.397+0000] {subprocess.py:106} INFO -   File "/home/airflow/.local/lib/python3.12/site-packages/dbt/parser/manifest.py", line 435, in load
[2025-02-13T08:21:25.398+0000] {subprocess.py:106} INFO -     self.parse_project(
[2025-02-13T08:21:25.398+0000] {subprocess.py:106} INFO -   File "/home/airflow/.local/lib/python3.12/site-packages/dbt/parser/manifest.py", line 733, in parse_project
[2025-02-13T08:21:25.399+0000] {subprocess.py:106} INFO -     parser.parse_file(block)
[2025-02-13T08:21:25.399+0000] {subprocess.py:106} INFO -   File "/home/airflow/.local/lib/python3.12/site-packages/dbt/parser/base.py", line 484, in parse_file
[2025-02-13T08:21:25.400+0000] {subprocess.py:106} INFO -     self.parse_node(file_block)
[2025-02-13T08:21:25.400+0000] {subprocess.py:106} INFO -   File "/home/airflow/.local/lib/python3.12/site-packages/dbt/parser/base.py", line 445, in parse_node
[2025-02-13T08:21:25.401+0000] {subprocess.py:106} INFO -     self.render_update(node, config)
[2025-02-13T08:21:25.401+0000] {subprocess.py:106} INFO -   File "/home/airflow/.local/lib/python3.12/site-packages/dbt/parser/models.py", line 348, in render_update
[2025-02-13T08:21:25.402+0000] {subprocess.py:106} INFO -     super().render_update(node, config)
[2025-02-13T08:21:25.402+0000] {subprocess.py:106} INFO -   File "/home/airflow/.local/lib/python3.12/site-packages/dbt/parser/base.py", line 421, in render_update
[2025-02-13T08:21:25.403+0000] {subprocess.py:106} INFO -     context = self.render_with_context(node, config)
[2025-02-13T08:21:25.403+0000] {subprocess.py:106} INFO -               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-02-13T08:21:25.404+0000] {subprocess.py:106} INFO -   File "/home/airflow/.local/lib/python3.12/site-packages/dbt/parser/base.py", line 270, in render_with_context
[2025-02-13T08:21:25.404+0000] {subprocess.py:106} INFO -     get_rendered(parsed_node.raw_code, context, parsed_node, capture_macros=True)
[2025-02-13T08:21:25.405+0000] {subprocess.py:106} INFO -   File "/home/airflow/.local/lib/python3.12/site-packages/dbt/clients/jinja.py", line 138, in get_rendered
[2025-02-13T08:21:25.405+0000] {subprocess.py:106} INFO -     template = get_template(
[2025-02-13T08:21:25.406+0000] {subprocess.py:106} INFO -                ^^^^^^^^^^^^^
[2025-02-13T08:21:25.406+0000] {subprocess.py:106} INFO -   File "/home/airflow/.local/lib/python3.12/site-packages/dbt_common/clients/jinja.py", line 565, in get_template
[2025-02-13T08:21:25.406+0000] {subprocess.py:106} INFO -     return env.from_string(template_source, globals=ctx)
[2025-02-13T08:21:25.407+0000] {subprocess.py:106} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-02-13T08:21:25.407+0000] {subprocess.py:106} INFO -   File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/environment.py", line 1111, in from_string
[2025-02-13T08:21:25.408+0000] {subprocess.py:106} INFO -     return cls.from_code(self, self.compile(source), gs, None)
[2025-02-13T08:21:25.408+0000] {subprocess.py:106} INFO -                                ^^^^^^^^^^^^^^^^^^^^
[2025-02-13T08:21:25.408+0000] {subprocess.py:106} INFO -   File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/environment.py", line 769, in compile
[2025-02-13T08:21:25.409+0000] {subprocess.py:106} INFO -     return self._compile(source, filename)
[2025-02-13T08:21:25.409+0000] {subprocess.py:106} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-02-13T08:21:25.409+0000] {subprocess.py:106} INFO -   File "/home/airflow/.local/lib/python3.12/site-packages/dbt_common/clients/jinja.py", line 125, in _compile
[2025-02-13T08:21:25.410+0000] {subprocess.py:106} INFO -     return super()._compile(source, filename)  # type: ignore
[2025-02-13T08:21:25.410+0000] {subprocess.py:106} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-02-13T08:21:25.411+0000] {subprocess.py:106} INFO -   File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/environment.py", line 709, in _compile
[2025-02-13T08:21:25.412+0000] {subprocess.py:106} INFO -     return compile(source, filename, "exec")
[2025-02-13T08:21:25.413+0000] {subprocess.py:106} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-02-13T08:21:25.413+0000] {subprocess.py:106} INFO -   File "<template>", line 15
[2025-02-13T08:21:25.414+0000] {subprocess.py:106} INFO - SyntaxError: keyword argument repeated: post_hook
[2025-02-13T08:21:25.414+0000] {subprocess.py:106} INFO - 
[2025-02-13T08:21:26.168+0000] {subprocess.py:110} INFO - Command exited with return code 2
[2025-02-13T08:21:26.181+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2025-02-13T08:21:26.186+0000] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=transform_data_dag, task_id=dbt_run, run_id=manual__2025-02-13T08:21:14.147237+00:00, execution_date=20250213T082114, start_date=20250213T082121, end_date=20250213T082126
[2025-02-13T08:21:26.215+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-02-13T08:21:26.216+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 69 for task dbt_run (Bash command failed. The command returned a non-zero exit code 2.; 5897)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2025-02-13T08:21:26.261+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-02-13T08:21:26.287+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-13T08:21:26.292+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
